# Generated by Django 3.1.3 on 2020-11-18 13:39

from django.db import migrations, models
import django.db.models.deletion
import roommate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roomie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('room', 'room'), ('flat', 'flat'), ('hostel', 'hostel')], max_length=30)),
                ('headline', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('price_range', models.CharField(choices=[('0-5000', '0-5000'), ('5001-10,000', '5001-10,000'), ('10001-15000', '10001-15000'), ('15001-20000', '15001-20000'), ('20000+', '20000+')], max_length=200)),
                ('sex_pref', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('male/female', 'male/female')], max_length=200)),
                ('age_pref', models.CharField(choices=[('15-20', '15-20'), ('21-25', '21-25'), ('26-30', '26-30'), ('31-35', '31-35'), ('36-40', '36-40'), ('40+', '40+')], max_length=200)),
                ('details', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=roommate.models.RoomieImage.generate_filename)),
                ('roomie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommate.roomie')),
            ],
        ),
    ]
