# Generated by Django 3.1.3 on 2021-02-24 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0003_auto_20201207_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomie',
            old_name='city',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='roomie',
            name='longitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
