# Generated by Django 3.1.3 on 2021-02-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='Popular/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('position', models.CharField(max_length=400)),
                ('pic', models.ImageField(upload_to='People/')),
                ('words', models.TextField()),
            ],
        ),
    ]
