# Generated by Django 3.1.3 on 2021-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='city_slug',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
