# Generated by Django 3.1.3 on 2021-02-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchingapp', '0005_cartitem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='profile',
        ),
    ]
