# Generated by Django 3.1.3 on 2021-03-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20210311_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='media/avatars/avatar.png', upload_to='avatars/'),
        ),
    ]
