# Generated by Django 3.1.3 on 2020-11-09 13:34

from django.db import migrations, models
import django.db.models.deletion
import searchingapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('room', 'room'), ('flat', 'flat'), ('house', 'house'), ('hostel', 'hostel'), ('land', 'land')], max_length=30)),
                ('headline', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_model', to='userprofile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=searchingapp.models.Image.generate_filename)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='searchingapp.item')),
            ],
        ),
    ]
