# Generated by Django 3.1.3 on 2021-02-24 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='city',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='item',
            name='longitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
