# Generated by Django 3.1.3 on 2021-02-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('searchingapp', '0005_cartitem_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
    ]
