# Generated by Django 3.1.3 on 2021-02-27 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('searchingapp', '0006_auto_20210226_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='searchingapp.item'),
        ),
    ]
